# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'importsettingsdialog.ui'
#
# Created: Wed Sep 16 18:55:03 2009
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_ImportSettingsDialog(object):
    def setupUi(self, ImportSettingsDialog):
        ImportSettingsDialog.setObjectName("ImportSettingsDialog")
        ImportSettingsDialog.resize(754, 509)
        self.buttonBox = QtGui.QDialogButtonBox(ImportSettingsDialog)
        self.buttonBox.setGeometry(QtCore.QRect(540, 470, 161, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.kineticsGroupBox = QtGui.QGroupBox(ImportSettingsDialog)
        self.kineticsGroupBox.setEnabled(True)
        self.kineticsGroupBox.setGeometry(QtCore.QRect(20, 250, 301, 211))
        self.kineticsGroupBox.setCheckable(True)
        self.kineticsGroupBox.setChecked(False)
        self.kineticsGroupBox.setObjectName("kineticsGroupBox")
        self.orientationGroupBox = QtGui.QGroupBox(self.kineticsGroupBox)
        self.orientationGroupBox.setGeometry(QtCore.QRect(20, 40, 122, 91))
        self.orientationGroupBox.setObjectName("orientationGroupBox")
        self.vertRadioButton = QtGui.QRadioButton(self.orientationGroupBox)
        self.vertRadioButton.setGeometry(QtCore.QRect(10, 30, 102, 21))
        self.vertRadioButton.setChecked(True)
        self.vertRadioButton.setObjectName("vertRadioButton")
        self.horRadioButton = QtGui.QRadioButton(self.orientationGroupBox)
        self.horRadioButton.setGeometry(QtCore.QRect(10, 50, 102, 21))
        self.horRadioButton.setObjectName("horRadioButton")
        self.startatGroupBox = QtGui.QGroupBox(self.kineticsGroupBox)
        self.startatGroupBox.setGeometry(QtCore.QRect(150, 40, 131, 91))
        self.startatGroupBox.setObjectName("startatGroupBox")
        self.bottomRadioButton = QtGui.QRadioButton(self.startatGroupBox)
        self.bottomRadioButton.setGeometry(QtCore.QRect(10, 30, 121, 21))
        self.bottomRadioButton.setChecked(True)
        self.bottomRadioButton.setObjectName("bottomRadioButton")
        self.topRadioButton = QtGui.QRadioButton(self.startatGroupBox)
        self.topRadioButton.setGeometry(QtCore.QRect(10, 50, 102, 21))
        self.topRadioButton.setObjectName("topRadioButton")
        self.widget = QtGui.QWidget(self.kineticsGroupBox)
        self.widget.setGeometry(QtCore.QRect(20, 140, 198, 58))
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtGui.QGridLayout(self.widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineshiftSpinBox = QtGui.QSpinBox(self.widget)
        self.lineshiftSpinBox.setMaximum(3999)
        self.lineshiftSpinBox.setProperty("value", QtCore.QVariant(256))
        self.lineshiftSpinBox.setObjectName("lineshiftSpinBox")
        self.gridLayout_2.addWidget(self.lineshiftSpinBox, 0, 0, 1, 1)
        self.lineshiftLabel = QtGui.QLabel(self.widget)
        self.lineshiftLabel.setObjectName("lineshiftLabel")
        self.gridLayout_2.addWidget(self.lineshiftLabel, 0, 1, 1, 1)
        self.stripsperframeSpinBox = QtGui.QSpinBox(self.widget)
        self.stripsperframeSpinBox.setMaximum(3999)
        self.stripsperframeSpinBox.setProperty("value", QtCore.QVariant(2))
        self.stripsperframeSpinBox.setObjectName("stripsperframeSpinBox")
        self.gridLayout_2.addWidget(self.stripsperframeSpinBox, 1, 0, 1, 1)
        self.lineshiftLabel_2 = QtGui.QLabel(self.widget)
        self.lineshiftLabel_2.setObjectName("lineshiftLabel_2")
        self.gridLayout_2.addWidget(self.lineshiftLabel_2, 1, 1, 1, 1)
        self.explanationTextEdit = QtGui.QTextEdit(ImportSettingsDialog)
        self.explanationTextEdit.setEnabled(False)
        self.explanationTextEdit.setGeometry(QtCore.QRect(360, 60, 371, 161))
        self.explanationTextEdit.setObjectName("explanationTextEdit")
        self.execTextEdit = QtGui.QTextEdit(ImportSettingsDialog)
        self.execTextEdit.setEnabled(True)
        self.execTextEdit.setGeometry(QtCore.QRect(360, 250, 371, 209))
        self.execTextEdit.setLineWrapMode(QtGui.QTextEdit.NoWrap)
        self.execTextEdit.setAcceptRichText(False)
        self.execTextEdit.setObjectName("execTextEdit")
        self.frameGroupBox = QtGui.QGroupBox(ImportSettingsDialog)
        self.frameGroupBox.setGeometry(QtCore.QRect(20, 60, 301, 171))
        self.frameGroupBox.setObjectName("frameGroupBox")
        self.widget1 = QtGui.QWidget(self.frameGroupBox)
        self.widget1.setGeometry(QtCore.QRect(31, 40, 241, 120))
        self.widget1.setObjectName("widget1")
        self.gridLayout = QtGui.QGridLayout(self.widget1)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtGui.QLabel(self.widget1)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.pwaSpinBox = QtGui.QSpinBox(self.widget1)
        self.pwaSpinBox.setObjectName("pwaSpinBox")
        self.gridLayout.addWidget(self.pwaSpinBox, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.widget1)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.pwoaSpinBox = QtGui.QSpinBox(self.widget1)
        self.pwoaSpinBox.setEnabled(True)
        self.pwoaSpinBox.setProperty("value", QtCore.QVariant(1))
        self.pwoaSpinBox.setObjectName("pwoaSpinBox")
        self.gridLayout.addWidget(self.pwoaSpinBox, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.widget1)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.df1SpinBox = QtGui.QSpinBox(self.widget1)
        self.df1SpinBox.setProperty("value", QtCore.QVariant(2))
        self.df1SpinBox.setObjectName("df1SpinBox")
        self.gridLayout.addWidget(self.df1SpinBox, 2, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.widget1)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.df2SpinBox = QtGui.QSpinBox(self.widget1)
        self.df2SpinBox.setProperty("value", QtCore.QVariant(2))
        self.df2SpinBox.setObjectName("df2SpinBox")
        self.gridLayout.addWidget(self.df2SpinBox, 3, 1, 1, 1)
        self.customfuncCheckBox = QtGui.QCheckBox(ImportSettingsDialog)
        self.customfuncCheckBox.setGeometry(QtCore.QRect(360, 228, 181, 23))
        self.customfuncCheckBox.setObjectName("customfuncCheckBox")
        self.widget2 = QtGui.QWidget(ImportSettingsDialog)
        self.widget2.setGeometry(QtCore.QRect(113, 21, 180, 28))
        self.widget2.setObjectName("widget2")
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtGui.QLabel(self.widget2)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.numberSpinBox = QtGui.QSpinBox(self.widget2)
        self.numberSpinBox.setMinimum(1)
        self.numberSpinBox.setProperty("value", QtCore.QVariant(3))
        self.numberSpinBox.setObjectName("numberSpinBox")
        self.horizontalLayout.addWidget(self.numberSpinBox)

        self.retranslateUi(ImportSettingsDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), ImportSettingsDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), ImportSettingsDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ImportSettingsDialog)

    def retranslateUi(self, ImportSettingsDialog):
        ImportSettingsDialog.setWindowTitle(QtGui.QApplication.translate("ImportSettingsDialog", "Image import settings", None, QtGui.QApplication.UnicodeUTF8))
        self.kineticsGroupBox.setTitle(QtGui.QApplication.translate("ImportSettingsDialog", "Split image (kinetics mode)", None, QtGui.QApplication.UnicodeUTF8))
        self.orientationGroupBox.setTitle(QtGui.QApplication.translate("ImportSettingsDialog", "Orientation", None, QtGui.QApplication.UnicodeUTF8))
        self.vertRadioButton.setText(QtGui.QApplication.translate("ImportSettingsDialog", "Vertical", None, QtGui.QApplication.UnicodeUTF8))
        self.horRadioButton.setText(QtGui.QApplication.translate("ImportSettingsDialog", "Horizontal", None, QtGui.QApplication.UnicodeUTF8))
        self.startatGroupBox.setTitle(QtGui.QApplication.translate("ImportSettingsDialog", "Start at", None, QtGui.QApplication.UnicodeUTF8))
        self.bottomRadioButton.setText(QtGui.QApplication.translate("ImportSettingsDialog", "Bottom / Right ", None, QtGui.QApplication.UnicodeUTF8))
        self.topRadioButton.setText(QtGui.QApplication.translate("ImportSettingsDialog", "Top / Left", None, QtGui.QApplication.UnicodeUTF8))
        self.lineshiftLabel.setText(QtGui.QApplication.translate("ImportSettingsDialog", "# of lines shifted", None, QtGui.QApplication.UnicodeUTF8))
        self.lineshiftLabel_2.setText(QtGui.QApplication.translate("ImportSettingsDialog", "# of strips per frame", None, QtGui.QApplication.UnicodeUTF8))
        self.explanationTextEdit.setHtml(QtGui.QApplication.translate("ImportSettingsDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'DejaVu Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">The processed image is usually defined as:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">(pwa - df1) / (pwoa - df2),</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">with corrections for zeros and negative values. To define a different processed image, use the text box below. Valid variables are: pwa, pwoa, df1, df2 and frames. \"frames\" is a list that can be indexed directly with the frame number. Arithmetic operations and valid Python expressions are allowed. Assign the wanted image to the variable \"result\".</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.frameGroupBox.setTitle(QtGui.QApplication.translate("ImportSettingsDialog", "Frame settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("ImportSettingsDialog", "Probe with atoms (pwa)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("ImportSettingsDialog", "Probe without atoms (pwoa)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("ImportSettingsDialog", "Dark field 1 (df1)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("ImportSettingsDialog", "Dark field 2 (df2)", None, QtGui.QApplication.UnicodeUTF8))
        self.customfuncCheckBox.setText(QtGui.QApplication.translate("ImportSettingsDialog", "Use custom function", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("ImportSettingsDialog", "Number of frames ", None, QtGui.QApplication.UnicodeUTF8))

